name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: macos-11.0
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  nowItIs:
    runs-on: macos-11.0
    steps:
      - name: Show date
        run: date
  directory_contents:
    runs-on: macos-11.0
    steps:
      - name: Show directory contents
        run: ls -l